<?php

namespace Database\Seeders;

use App\Models\Role;
use Illuminate\Database\Seeder;

class RoleSeeder extends Seeder
{
    /**
     * Seed the roles table with all BASA system roles.
     * roleID is auto-generated by the Role model (Role-001, Role-002, ...).
     * All permission flags default to TRUE.
     */
    public function run(): void
    {
        $roles = [
            'Super Admin',
            'School Admin',
            'Principal',
            'Academic Coordinator',
            'Accountant',
            'Inventory Manager',
            'Teacher',
            'Class Teacher',
            'Librarian',
            'Hostel Warden',
            'Transport-in-Charge',
            'Admission Officer',
            'Event Coordinator',
            'Club Adviser',
            'Guidance Counselor',
            'School Nurse',
            'Parent / Guardian',
            'Student',
            'Alumni',
        ];

        foreach ($roles as $roleName) {
            Role::firstOrCreate(
                ['name' => $roleName, 'guard_name' => 'web'],
                ['roleName' => $roleName]
            );
        }

        $this->command->info('✅ ' . count($roles) . ' roles seeded successfully.');
    }
}
